wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684006571.589758
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.11.1
      5: 0.15.2
      6: 4.29.1
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
lr:
  desc: null
  value: 0.01
